"""add friendship

Revision ID: 00003
Revises: 00002
Create Date: 2025-12-26 12:08:54.714329

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00003"
down_revision: Union[str, Sequence[str], None] = "00002"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "friendships",
        sa.Column("requester_id", sa.Uuid(), nullable=False),
        sa.Column("addressee_id", sa.Uuid(), nullable=False),
        sa.Column("status", sa.String(length=50), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["addressee_id"], ["users.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["requester_id"], ["users.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
        sa.UniqueConstraint(
            "requester_id", "addressee_id", name="uq_friendship_req_addr"
        ),
    )
    op.create_index(
        op.f("ix_friendships_addressee_id"),
        "friendships",
        ["addressee_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_friendships_created_at"), "friendships", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_friendships_requester_id"),
        "friendships",
        ["requester_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_friendships_requester_id"), table_name="friendships")
    op.drop_index(op.f("ix_friendships_created_at"), table_name="friendships")
    op.drop_index(op.f("ix_friendships_addressee_id"), table_name="friendships")
    op.drop_table("friendships")
    # ### end Alembic commands ###
