"""add_challenges

Revision ID: 00004
Revises: 00003
Create Date: 2025-12-27 10:28:34.640782

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "00004"
down_revision: Union[str, Sequence[str], None] = "00003"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "challenges",
        sa.Column("creator_id", sa.Uuid(), nullable=False),
        sa.Column("source_run_id", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["creator_id"], ["users.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["source_run_id"], ["runs.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_challenges_created_at"), "challenges", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_challenges_creator_id"), "challenges", ["creator_id"], unique=False
    )
    op.create_table(
        "challenge_attempts",
        sa.Column("challenge_id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("run_id", sa.Uuid(), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["challenge_id"], ["challenges.uuid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["run_id"], ["runs.uuid"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_challenge_attempts_challenge_id"),
        "challenge_attempts",
        ["challenge_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_challenge_attempts_created_at"),
        "challenge_attempts",
        ["created_at"],
        unique=False,
    )
    op.create_index(
        op.f("ix_challenge_attempts_user_id"),
        "challenge_attempts",
        ["user_id"],
        unique=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        op.f("ix_challenge_attempts_user_id"), table_name="challenge_attempts"
    )
    op.drop_index(
        op.f("ix_challenge_attempts_created_at"), table_name="challenge_attempts"
    )
    op.drop_index(
        op.f("ix_challenge_attempts_challenge_id"), table_name="challenge_attempts"
    )
    op.drop_table("challenge_attempts")
    op.drop_index(op.f("ix_challenges_creator_id"), table_name="challenges")
    op.drop_index(op.f("ix_challenges_created_at"), table_name="challenges")
    op.drop_table("challenges")
    # ### end Alembic commands ###
