"""add goal, achievement models

Revision ID: 00002
Revises: 00001
Create Date: 2025-11-23 18:21:42.845915

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "00002"
down_revision: Union[str, Sequence[str], None] = "00001"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "achievements",
        sa.Column("user_uuid", sa.Uuid(), nullable=False),
        sa.Column("title", sa.String(length=255), nullable=False),
        sa.Column("description", sa.String(length=1024), nullable=True),
        sa.Column("earned_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "achievement_type",
            sa.String(length=50),
            nullable=False,
            comment="Type of achievement e.g. GOAL_COMPLETION, MILESTONE",
        ),
        sa.Column(
            "meta_data",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="Additional data e.g. goal_id, run_id",
        ),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_uuid"], ["users.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(
        op.f("ix_achievements_created_at"), "achievements", ["created_at"], unique=False
    )
    op.create_index(
        op.f("ix_achievements_user_uuid"), "achievements", ["user_uuid"], unique=False
    )
    op.create_table(
        "goals",
        sa.Column("user_uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "goal_type",
            sa.Enum("DISTANCE", "DURATION", "NUMBER_OF_RUNS", name="goaltype"),
            nullable=False,
        ),
        sa.Column(
            "target",
            sa.Integer(),
            nullable=False,
            comment="Target value: distance in km, duration in minutes, or number of runs",
        ),
        sa.Column(
            "time_period",
            sa.Enum("WEEKLY", "MONTHLY", "YEARLY", name="timeperiod"),
            nullable=False,
        ),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_uuid"], ["users.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_goals_created_at"), "goals", ["created_at"], unique=False)
    op.create_index(op.f("ix_goals_user_uuid"), "goals", ["user_uuid"], unique=False)
    op.create_table(
        "runs",
        sa.Column("user_uuid", sa.Uuid(), nullable=False),
        sa.Column("name", sa.String(length=255), nullable=True),
        sa.Column("start_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column("end_time", sa.DateTime(timezone=True), nullable=False),
        sa.Column(
            "duration", sa.Float(), nullable=False, comment="Duration in minutes"
        ),
        sa.Column("distance", sa.Float(), nullable=False, comment="Distance in km"),
        sa.Column("calories", sa.Integer(), nullable=True),
        sa.Column(
            "route",
            postgresql.JSONB(astext_type=sa.Text()),
            nullable=True,
            comment="List of route points: lat, lng, accuracy, altitude, speed, timestamp",
        ),
        sa.Column("uuid", sa.Uuid(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["user_uuid"], ["users.uuid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("uuid"),
    )
    op.create_index(op.f("ix_runs_created_at"), "runs", ["created_at"], unique=False)
    op.create_index(op.f("ix_runs_user_uuid"), "runs", ["user_uuid"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_runs_user_uuid"), table_name="runs")
    op.drop_index(op.f("ix_runs_created_at"), table_name="runs")
    op.drop_table("runs")
    op.drop_index(op.f("ix_goals_user_uuid"), table_name="goals")
    op.drop_index(op.f("ix_goals_created_at"), table_name="goals")
    op.drop_table("goals")
    op.drop_index(op.f("ix_achievements_user_uuid"), table_name="achievements")
    op.drop_index(op.f("ix_achievements_created_at"), table_name="achievements")
    op.drop_table("achievements")
    # ### end Alembic commands ###
